apiVersion: modules.krateo.io/v1
kind: Core
metadata:
  name: core
spec:
  namespace: krateo-system
  platform: openshift
  protocol: https
  domain: krateoplatformops.io
  domainPort: 443
  app:
    hostname: app
  api:
    hostname: api
  argo-cd:
    hostname: argocd
  notification-service:
    hostname: notification
