apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: krateo-module-core
spec:
  package: ghcr.io/krateoplatformops/krateo-module-core:v1.0.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
