apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: krateo-module-core
spec:
  package: ghcr.io/krateoplatformops/krateo-module-core:latest
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
