---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: core.modules.krateo.io
spec:
  compositeTypeRef:
    apiVersion: modules.krateo.io/v1
    kind: Core
  resources:
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
      readinessChecks:
        - type: None
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: app
        spec:
          forProvider:
            chart:
              name: app
              repository: https://charts.krateo.io
              version: 1.2.22
            namespace: krateo-system
            values:
              fullnameOverride: app
      patches:
        - fromFieldPath: spec.app.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-app"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: argocd
        spec:
          forProvider:
            chart:
              name: argocd-service
              repository: https://charts.krateo.io
              version: 1.0.7
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.argocd-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-argocd-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: auth
        spec:
          forProvider:
            chart:
              name: auth-service
              repository: https://charts.krateo.io
              version: 1.2.0
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.auth-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-auth-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: deployment
        spec:
          forProvider:
            chart:
              name: deployment-service
              repository: https://charts.krateo.io
              version: 1.2.25
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.deployment-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-deployment-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: git
        spec:
          forProvider:
            chart:
              name: git-service
              repository: https://charts.krateo.io
              version: 1.0.9
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.git-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-git-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
#    - base:
#        apiVersion: helm.crossplane.io/v1beta1
#        kind: Release
#        metadata:
#          annotations:
#            crossplane.io/external-name: kubernetes
#        spec:
#          forProvider:
#            chart:
#              name: kubernetes-service
#              repository: https://charts.krateo.io
#              version: 1.1.1
#            namespace: krateo-system
#      patches:
#        - fromFieldPath: spec.kubernetes-service.version
#          toFieldPath: spec.forProvider.chart.version
#        - fromFieldPath: metadata.name
#          toFieldPath: metadata.name
#          transforms:
#            - type: string
#              string:
#                fmt: "%s-release-kubernetes-service"
#        - fromFieldPath: metadata.name
#          toFieldPath: spec.providerConfigRef.name
#          transforms:
#            - type: string
#              string:
#                fmt: "%s-provider-helm-pc-in"
#        - fromFieldPath: spec.namespace
#          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: event
        spec:
          forProvider:
            chart:
              name: event-service
              repository: https://charts.krateo.io
              version: 1.1.6
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.event-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-event-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: notification
        spec:
          forProvider:
            chart:
              name: notification-service
              repository: https://charts.krateo.io
              version: 1.1.6
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.notification-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-notification-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        # - type: CombineFromComposite
        #   combine:
        #     variables:
        #       - fromFieldPath: spec.notification-service.hostname
        #       - fromFieldPath: spec.domain
        #     strategy: string
        #     string:
        #       fmt: "%s.%s"
        #   toFieldPath: spec.forProvider.values.ingress.host
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: template
        spec:
          forProvider:
            chart:
              name: template-service
              repository: https://charts.krateo.io
              version: 1.2.6
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.template-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-template-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: secret
        spec:
          forProvider:
            chart:
              name: secret-service
              repository: https://charts.krateo.io
              version: 1.1.4
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.secret-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-secret-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: pipeline
        spec:
          forProvider:
            chart:
              name: pipeline-service
              repository: https://charts.krateo.io
              version: 1.1.2
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.pipeline-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-pipeline-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-k8s-pc-in"
      readinessChecks:
        - type: None
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: provider
        spec:
          forProvider:
            chart:
              name: provider-service
              repository: https://charts.krateo.io
              version: 1.0.8
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.provider-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-provider-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: component
        spec:
          forProvider:
            chart:
              name: component-service
              repository: https://charts.krateo.io
              version: 0.2.1
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.component-service.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-component-service"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          annotations:
            crossplane.io/external-name: eventrouter
        spec:
          forProvider:
            chart:
              name: eventrouter
              repository: https://charts.krateo.io
              version: 0.3.1
            namespace: krateo-system
      patches:
        - fromFieldPath: spec.eventrouter.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-release-eventrouter"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-helm-pc-in"
        - fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: ProviderConfig
        spec:
          credentials:
            source: InjectedIdentity
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-k8s-pc-in"
      readinessChecks:
        - type: None
    - base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: eventrouter.krateo.io/v1alpha1
              kind: Registration
              metadata:
                name: event-service-registration
              spec:
                serviceName: event-service
                endpoint: http://event-service.krateo-system.svc
      patches:
        - fromFieldPath: "metadata.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-event-service-registration-object"
        - fromFieldPath: metadata.name
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-provider-k8s-pc-in"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
