---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: core.modules.krateo.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: modules.krateo.io
  names:
    kind: Core
    listKind: CoreList
    plural: core
    singular: core
  versions:
    - name: v1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          description: Core module of Krateo PlatformOps
          properties:
            spec:
              properties:
                platform:
                  description: Kubernetes distribution for Krateo, i.e. kubernetes, openshift
                  type: string
                  enum:
                  - kubernetes
                  - openshift
                  # default:
                  #   kubernetes
                namespace:
                  description: Kubernetes namespace for Krateo, i.e. krateo-system
                  type: string
                  # default: krateo-system
                protocol:
                  description: protocol of uris, i.e. http or https
                  type: string
                  default: https
                domain:
                  description: domain of uris, i.e. krateo.site
                  type: string
                domainPort:
                  description: port of uris, i.e. <domain>:32000
                  type: integer
                  default: 443
                kongapigw:
                  description: kongapigw helm chart values
                  type: object
                  properties:
                    version:
                      description: kongapigw helm chart version
                      type: string
                    postgresql:
                      description: kongapigw helm chart postgresql values
                      type: object
                      properties:
                        enabled:
                          description: kongapigw helm chart postgresql enabled
                          type: boolean
                    admin:
                      description: kongapigw helm chart admin values
                      type: object
                      properties:
                        enabled:
                          description: kongapigw helm chart admin enabled
                          type: boolean
                        http:
                          description: kongapigw helm chart admin http values
                          type: object
                          properties:
                            enabled:
                              description: kongapigw helm chart admin http enabled
                              type: boolean
                        https:
                          description: kongapigw helm chart admin https values
                          type: object
                          properties:
                            enabled:
                              description: kongapigw helm chart admin https enabled
                              type: boolean
                        type:
                          description: kongapigw helm chart admin service type
                          type: string
                    proxy:
                      description: kongapigw helm chart proxy values
                      type: object
                      properties:
                        type:
                          description: kongapigw helm chart proxy service type
                          type: string
                        http:
                          description: kongapigw helm chart proxy http values
                          type: object
                          properties:
                            nodePort:
                              description: kongapigw helm chart proxy http nodePort value
                              type: integer
                        https:
                          description: kongapigw helm chart proxy https values
                          type: object
                          properties:
                            nodePort:
                              description: kongapigw helm chart proxy https nodePort value
                              type: integer

                        loadBalancerIP:
                          type: string
                argo-cd:
                  description: argo-cd helm chart values
                  type: object
                  properties:
                    version:
                      description: argo-cd helm chart version
                      type: string
                    hostname:
                      description: hostname of argo-cd, i.e. argo-cd.<domain>
                      type: string
                      default: argocd
                    service:
                      description: service of argo-cd
                      type: object
                      properties:
                        http:
                          description: service http of argo-cd
                          type: object
                          properties:
                            port:
                              description: service http port of argo-cd
                              type: integer
                dashboard-common-chart:
                  description: dashboard-common-chart helm chart values
                  type: object
                  properties:
                    version:
                      description: dashboard-common-chart helm chart version
                      type: string
                    mongodb:
                      description: dashboard-common-chart helm chart mongodb values
                      type: object
                      properties:
                        uri:
                          description: dashboard-common-chart helm chart mongodb uri
                          type: string
                app:
                  description: app helm chart values
                  type: object
                  properties:
                    version:
                      description: app helm chart version
                      type: string
                    hostname:
                      description: hostname of app, i.e. app.<domain>
                      type: string
                      default: app
                    service:
                      description: service of app
                      type: object
                      properties:
                        http:
                          description: service http of app
                          type: object
                          properties:
                            port:
                              description: service http port of app
                              type: integer
                    # ingress:
                    #   description: ingress values
                    #   type: object
                    #   properties:
                    #     enabled:
                    #       description: ingress enabled value
                    #       type: boolean
                    #     annotations:
                    #       description: ingress annotations values
                    #       type: object
                    #     tls:
                    #       description: ingress tls values
                    #       type: object
                    #       properties:
                    #         enabled:
                    #           description: ingress tls enabled value
                    #           type: boolean
                    #         secret:
                    #           description: ingress tls secret values
                    #           type: object
                    #           properties:
                    #             create:
                    #               description: ingress tls secret create value
                    #               type: boolean
                    #             name:
                    #               description: name will only be used, if create is set to false to bind an existing secret. Otherwise the name will be automatically generated to avoid conflicts between multiple chart installations.
                    #               type: string
                    #       cert:
                    #         description: ingress cert will only be used, if the secret will be created by this chart
                    #         type: string
                    #       key:
                    #         description: ingress key will only be used, if the secret will be created by this chart
                    #         type: string
                api:
                  description: api helm chart values
                  type: object
                  properties:
                    version:
                      description: api helm chart version
                      type: string
                    hostname:
                      description: hostname of api, i.e. api.<domain>
                      type: string
                      default: api
                argocd-service:
                  description: argocd-service helm chart values
                  type: object
                  properties:
                    version:
                      description: argo-service helm chart version
                      type: string
                auth-service:
                  description: auth-service helm chart values
                  type: object
                  properties:
                    version:
                      description: auth-service helm chart version
                      type: string
                deployment-service:
                  description: deployment-service helm chart values
                  type: object
                  properties:
                    version:
                      description: deployment-service helm chart version
                      type: string
                git-service:
                  description: git-service helm chart values
                  type: object
                  properties:
                    version:
                      description: git-service helm chart version
                      type: string
                kubernetes-service:
                  description: kubernetes-service helm chart values
                  type: object
                  properties:
                    version:
                      description: kubernetes-service helm chart version
                      type: string
                event-service:
                  description: event-service helm chart values
                  type: object
                  properties:
                    version:
                      description: event-service helm chart version
                      type: string
                notification-service:
                  description: notification-service helm chart values
                  type: object
                  properties:
                    version:
                      description: notification-service helm chart version
                      type: string
                template-service:
                  description: template-service helm chart values
                  type: object
                  properties:
                    version:
                      description: template-service helm chart version
                      type: string
                secret-service:
                  description: secret-service helm chart values
                  type: object
                  properties:
                    version:
                      description: secret-service helm chart version
                      type: string
                pipeline-service:
                  description: pipeline-service helm chart values
                  type: object
                  properties:
                    version:
                      description: pipeline-service helm chart version
                      type: string
                eventrouter:
                  description: eventrouter helm chart values
                  type: object
                  properties:
                    version:
                      description: eventrouter helm chart version
                      type: string
